include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_CONTACT mihail_160505@@mail.ru)
set(CPACK_PACKAGE_VERSION ${PRINT_VERSION})
set(CPACK_PACKAGE_NAME "matrix")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "static C++ library for matrix")
set(CPACK_PACKAGE_VENDOR "kuznetsovvvv")
set(CPACK_PACKAGE_PACK_NAME "matrix-${PRINT_VERSION}")

set(CPACK_SOURCE_INSTALLED_DIRECTORIES 
  "${CMAKE_SOURCE_DIR}/matrix_application;${CMAKE_SOURCE_DIR}/matrix_lib")

set(CPACK_RESOURCE_FILE_README ${CMAKE_CURRENT_SOURCE_DIR}/README.md)

set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")

set(CPACK_DEBIAN_PACKAGE_PREDEPENDS "cmake >= 3.0")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)

set(CPACK_DEBIAN_PACKAGE_VERSION ${PRINT_VERSION})
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "all")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "matrix")

set(CPACK_GENERATOR "DEB;RPM")

set(CPACK_RPM_PACKAGE_SUMMARY "matrix")

include(CPack)
